{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-security",
    "version": "3.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.14"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-config",
          "version": {
            "requires": "6.3.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "6.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-security-3.3.5.jar",
          "url": "spring-boot-starter-security-3.3.5.jar",
          "size": 4742,
          "sha512": "f230deaa1ad45b1ea3981daee70208ec94b9bfc531706dedfafa1ff957eaa4ef9bb8cea2f28ac68cf4020962782f00a442cde79e7ce46228d06d93e2e3ccd120",
          "sha256": "8db280cf0dc3d2b10f14a787c01a1add88f79b918acc1c917cac75be66e8259e",
          "sha1": "662a0cd1672e55cdde5f8af1be79e18653e13c3d",
          "md5": "1a257ebbead1d57de44475188ea93935"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.14"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-config",
          "version": {
            "requires": "6.3.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "6.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-security-3.3.5.jar",
          "url": "spring-boot-starter-security-3.3.5.jar",
          "size": 4742,
          "sha512": "f230deaa1ad45b1ea3981daee70208ec94b9bfc531706dedfafa1ff957eaa4ef9bb8cea2f28ac68cf4020962782f00a442cde79e7ce46228d06d93e2e3ccd120",
          "sha256": "8db280cf0dc3d2b10f14a787c01a1add88f79b918acc1c917cac75be66e8259e",
          "sha1": "662a0cd1672e55cdde5f8af1be79e18653e13c3d",
          "md5": "1a257ebbead1d57de44475188ea93935"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-security-3.3.5-javadoc.jar",
          "url": "spring-boot-starter-security-3.3.5-javadoc.jar",
          "size": 4742,
          "sha512": "f230deaa1ad45b1ea3981daee70208ec94b9bfc531706dedfafa1ff957eaa4ef9bb8cea2f28ac68cf4020962782f00a442cde79e7ce46228d06d93e2e3ccd120",
          "sha256": "8db280cf0dc3d2b10f14a787c01a1add88f79b918acc1c917cac75be66e8259e",
          "sha1": "662a0cd1672e55cdde5f8af1be79e18653e13c3d",
          "md5": "1a257ebbead1d57de44475188ea93935"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-security-3.3.5-sources.jar",
          "url": "spring-boot-starter-security-3.3.5-sources.jar",
          "size": 4742,
          "sha512": "f230deaa1ad45b1ea3981daee70208ec94b9bfc531706dedfafa1ff957eaa4ef9bb8cea2f28ac68cf4020962782f00a442cde79e7ce46228d06d93e2e3ccd120",
          "sha256": "8db280cf0dc3d2b10f14a787c01a1add88f79b918acc1c917cac75be66e8259e",
          "sha1": "662a0cd1672e55cdde5f8af1be79e18653e13c3d",
          "md5": "1a257ebbead1d57de44475188ea93935"
        }
      ]
    }
  ]
}
