import { zodResolver } from "@hookform/resolvers/zod";
import { Save } from "lucide-react";
import { useEffect } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import type { Product, ProductInput } from "@/types/product";

const schema = z.object({ name: z.string().min(2, "Informe o nome do produto"), category: z.string().min(1, "Selecione uma categoria"), description: z.string().optional(), barcode: z.string().optional(), imageUrl: z.string().url("Informe uma URL válida").or(z.literal("")), status: z.enum(["ACTIVE", "INACTIVE"]) });
type ProductFormValues = z.infer<typeof schema>;
const fieldClass = "mt-2 h-11 w-full rounded-xl border bg-white px-3 text-sm outline-none focus:border-brand-500 focus:ring-3 focus:ring-brand-100 dark:bg-slate-900 dark:focus:ring-brand-500/20";
type Props = { product?: Product; submitting?: boolean; onSubmit: (input: ProductInput) => void; };
export function ProductForm({ product, submitting, onSubmit }: Props) { const { register, handleSubmit, reset, formState: { errors } } = useForm<ProductFormValues>({ resolver: zodResolver(schema), defaultValues: { name: "", category: "", description: "", barcode: "", imageUrl: "", status: "ACTIVE" } }); useEffect(() => { if (product) reset({ name: product.name, category: product.category, description: product.description ?? "", barcode: product.barcode ?? "", imageUrl: product.imageUrl ?? "", status: product.status }); }, [product, reset]); function submit(values: ProductFormValues) { onSubmit({ ...values, imageUrl: values.imageUrl || undefined }); } return <form onSubmit={handleSubmit(submit)} className="space-y-5" noValidate><div className="grid gap-5 md:grid-cols-2"><label><span className="text-sm font-bold">Nome</span><Input className="mt-2" placeholder="Ex.: Arroz Tipo 1" aria-invalid={Boolean(errors.name)} {...register("name")} />{errors.name && <span className="mt-1 block text-xs text-red-600">{errors.name.message}</span>}</label><label><span className="text-sm font-bold">Categoria</span><select className={fieldClass} aria-invalid={Boolean(errors.category)} {...register("category")}><option value="">Selecione</option><option value="Mercearia">Mercearia</option><option value="Hortifruti">Hortifruti</option><option value="Laticínios">Laticínios</option><option value="Limpeza">Limpeza</option></select>{errors.category && <span className="mt-1 block text-xs text-red-600">{errors.category.message}</span>}</label></div><label className="block"><span className="text-sm font-bold">Descrição <span className="font-normal text-slate-500">(opcional)</span></span><textarea className={`${fieldClass} h-28 py-3`} placeholder="Detalhes sobre o produto" {...register("description")} /></label><div className="grid gap-5 md:grid-cols-2"><label><span className="text-sm font-bold">Código de barras <span className="font-normal text-slate-500">(opcional)</span></span><Input className="mt-2" placeholder="789..." {...register("barcode")} /></label><label><span className="text-sm font-bold">Imagem (URL) <span className="font-normal text-slate-500">(opcional)</span></span><Input className="mt-2" placeholder="https://..." aria-invalid={Boolean(errors.imageUrl)} {...register("imageUrl")} />{errors.imageUrl && <span className="mt-1 block text-xs text-red-600">{errors.imageUrl.message}</span>}</label></div><label className="block max-w-xs"><span className="text-sm font-bold">Status</span><select className={fieldClass} {...register("status")}><option value="ACTIVE">Ativo</option><option value="INACTIVE">Inativo</option></select></label><div className="flex justify-end border-t pt-5"><Button type="submit" size="lg" disabled={submitting}><Save className="size-4" />{submitting ? "Salvando..." : "Salvar produto"}</Button></div></form>; }
