-- Atualização aditiva para instalações existentes com ddl-auto=validate.
-- Revisar e aplicar antes de iniciar a nova versão. Não remove dados existentes.
BEGIN;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS grupo_comparacao VARCHAR(255);
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS quantidade_medida NUMERIC(12,3);
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS tipo_medida VARCHAR(255);
ALTER TABLE mercados ADD COLUMN IF NOT EXISTS imagem_id UUID;
CREATE TABLE IF NOT EXISTS imagens (
    id UUID PRIMARY KEY,
    usuario_id BIGINT,
    content_type VARCHAR(255) NOT NULL,
    conteudo BYTEA NOT NULL
);
CREATE TABLE IF NOT EXISTS oferta_imagens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id BIGINT NOT NULL,
    mercado_id BIGINT NOT NULL,
    imagem_id UUID,
    UNIQUE (produto_id, mercado_id)
);
CREATE TABLE IF NOT EXISTS colecoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255), descricao VARCHAR(255), imagem_id UUID,
    ativo BOOLEAN NOT NULL DEFAULT TRUE, ordem INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS colecao_produtos (
    colecao_id BIGINT NOT NULL REFERENCES colecoes(id),
    produto_id BIGINT NOT NULL,
    PRIMARY KEY (colecao_id, produto_id)
);
COMMIT;
