-- Exemplo de criação para PostgreSQL. Não é aplicado automaticamente pela API.
CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    telefone VARCHAR(30),
    perfil VARCHAR(30) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    categoria VARCHAR(255),
    unidade_medida VARCHAR(255),
    marca VARCHAR(255),
    descricao VARCHAR(1000),
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS mercados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    endereco VARCHAR(255),
    bairro VARCHAR(255),
    cidade VARCHAR(255),
    estado VARCHAR(255),
    telefone VARCHAR(50),
    vendedor_id BIGINT,
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS precos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id BIGINT NOT NULL,
    mercado_id BIGINT NOT NULL,
    usuario_cadastro_id BIGINT,
    valor DECIMAL(10,2) NOT NULL CHECK (valor > 0),
    data_coleta DATE NOT NULL,
    observacao VARCHAR(255),
    data_cadastro TIMESTAMP,
    data_atualizacao TIMESTAMP,
    CONSTRAINT fk_preco_produto FOREIGN KEY (produto_id) REFERENCES produtos(id),
    CONSTRAINT fk_preco_mercado FOREIGN KEY (mercado_id) REFERENCES mercados(id),
    CONSTRAINT fk_preco_usuario FOREIGN KEY (usuario_cadastro_id) REFERENCES usuarios(id)
);

CREATE TABLE IF NOT EXISTS listas_compra (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    nome_lista VARCHAR(255) NOT NULL,
    data_criacao DATE NOT NULL,
    CONSTRAINT fk_lista_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE TABLE IF NOT EXISTS itens_lista_compra (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lista_compra_id BIGINT NOT NULL,
    produto_id BIGINT NOT NULL,
    quantidade INT NOT NULL CHECK (quantidade BETWEEN 1 AND 999),
    CONSTRAINT fk_item_lista FOREIGN KEY (lista_compra_id) REFERENCES listas_compra(id),
    CONSTRAINT fk_item_produto FOREIGN KEY (produto_id) REFERENCES produtos(id)
);

-- Para concluir o schema da experiência de compra, aplique também migrations-retail.sql.
