spring.application.name=quantota

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/quantota}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}
spring.jpa.defer-datasource-initialization=true

server.port=${SERVER_PORT:8080}
