{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-config",
    "version": "6.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.3.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.14"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.14"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.14"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.14"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-config-6.3.4.jar",
          "url": "spring-security-config-6.3.4.jar",
          "size": 1907884,
          "sha512": "b71604eab81441331a41d47019bbc34b2aa843dbb0668b625f10dd44a2d5feddd46fe9d9a284a09181002ff59a8dd8bad1f1a0c45656d9c3821cd130081d8e07",
          "sha256": "3a9e8aa87ac383c5c458af094d231faf0bd42c7ef56e95ee6dbc86209c77863c",
          "sha1": "ef05a0653492b58f3cfb11f5ee4b69007e259f57",
          "md5": "22cf7dabd6c9da8bee5209c1fd1c86b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.3.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.14"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.14"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.14"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.14"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-config-6.3.4.jar",
          "url": "spring-security-config-6.3.4.jar",
          "size": 1907884,
          "sha512": "b71604eab81441331a41d47019bbc34b2aa843dbb0668b625f10dd44a2d5feddd46fe9d9a284a09181002ff59a8dd8bad1f1a0c45656d9c3821cd130081d8e07",
          "sha256": "3a9e8aa87ac383c5c458af094d231faf0bd42c7ef56e95ee6dbc86209c77863c",
          "sha1": "ef05a0653492b58f3cfb11f5ee4b69007e259f57",
          "md5": "22cf7dabd6c9da8bee5209c1fd1c86b9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-config-6.3.4-javadoc.jar",
          "url": "spring-security-config-6.3.4-javadoc.jar",
          "size": 1125633,
          "sha512": "373fe2d4212a477acbd4496817cf1016e9731d292e32fbb07590d3216bdbc5b580ab8c3ffe4b9315f2f5925ddf80b825fe32ed32659af17d2a28fc83499b82c9",
          "sha256": "8a2d0f0fb3b91d657a802517fb7b82aa18709d81b172922c8e74bfa702f427a5",
          "sha1": "7aa4d08f01fb252faffac52c3d2a7ca05faa1303",
          "md5": "50412242dcf42eb763d3640fb9d6e603"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-config-6.3.4-sources.jar",
          "url": "spring-security-config-6.3.4-sources.jar",
          "size": 1310254,
          "sha512": "55c82297408e74233101d1257dd7391823e3d6e5d6d76c2a983c99946439bb8c8bc7cb926a94eda8d4048e69d88e0ebb2449659cad6e6190160dacdf4e25443f",
          "sha256": "5cff4ac8c810464ab4da05e5c8731cac8d871e339718a4a9bf09f84c25fd1a10",
          "sha1": "4e47c113dcadae3573233875ab8981a0fd1af04d",
          "md5": "dc54a1d70cc838c1be973f98dcc0f14d"
        },
        {
          "name": "spring-security-config-6.3.4-sources.jar",
          "url": "spring-security-config-6.3.4-sources.jar",
          "size": 1310254,
          "sha512": "55c82297408e74233101d1257dd7391823e3d6e5d6d76c2a983c99946439bb8c8bc7cb926a94eda8d4048e69d88e0ebb2449659cad6e6190160dacdf4e25443f",
          "sha256": "5cff4ac8c810464ab4da05e5c8731cac8d871e339718a4a9bf09f84c25fd1a10",
          "sha1": "4e47c113dcadae3573233875ab8981a0fd1af04d",
          "md5": "dc54a1d70cc838c1be973f98dcc0f14d"
        }
      ]
    }
  ]
}
